services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: unless-stopped
    userns_mode: keep-id:uid=1000,gid=1000
    ports:
      - "25565:25565"     # gameserver
      - "24454:24454/udp" # simple voice chat mod
      - "25585:25585"     # prometheus metrics (fabric exporter mod)
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.10"
      MEMORY: "5120M"
      MAX_PLAYERS: "25"
      MOTD: "oce test server"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Pacific/Auckland"
      DIFFICULTY: "3"
      VIEW_DISTANCE: "12"
      SPAWN_PROTECTION: "0"
      REGION_FILE_COMPRESSION: "lz4"
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        JustPyrrha
        Blizzardkitten
      PACKWIZ_URL: "https://github.com/JustPyrrha/oce-pack/raw/refs/heads/main/pack.toml"
      VANILLATWEAKS_SHARECODE: "TCKAO0\nFF8soj"
      RESOURCE_PACK: "https://github.com/JustPyrrha/oce-pack/raw/refs/heads/main/server-testing-pack.zip"
      RESOURCE_PACK_SHA1: "cfd8a88bc935d0586b4af510aac1b441796074a0"
      RESOURCE_PACK_REQUIRED: "true"
      BUG_REPORT_LINK: "https://github.com/JustPyrha/oce-pack/issues"
      ENABLE_ROLLING_LOGS: "true"
      LOG_TIMESTAMP: "true"
      LOG_IPS: "true"
    volumes:
      - "${PWD}/data:/data:Z"

x-podman:
  in_pod: false
