hash-format = "sha256"

[[files]]
file = ".github/workflows/release.yml"
hash = "f9b4a77037dfb2cf5439fc5a77e3a3e92f952da7d08e6269d23db21298ffb8f4"

[[files]]
file = "datapacks/armor-statues-datapack.pw.toml"
hash = "c9d215756d276588de476a1b5905bef6c7b0f0e138de8064aa94cdc28533bf10"
metafile = true

[[files]]
file = "datapacks/data-afk-display.pw.toml"
hash = "d41901f536cfabcd6f4f8d75426e57401694cdf72577f9386e960290ee7f3dd5"
metafile = true

[[files]]
file = "datapacks/data-anti-enderman-grief.pw.toml"
hash = "f77ab347cbbfcc7a8523868e8bce0e6c42500b3e364d72d07ec8c5cb04b75102"
metafile = true

[[files]]
file = "datapacks/data-camera.pw.toml"
hash = "e58a68842bbe66b3728de3abff675a170a03ff038db11587f0491c8a3c69b7a3"
metafile = true

[[files]]
file = "datapacks/data-cave-cleaner.pw.toml"
hash = "54c70c72e865c93082ba73c015b46392778da66662eb044b07151d1683713639"
metafile = true

[[files]]
file = "datapacks/data-coordinates-hud.pw.toml"
hash = "d27b5bb088234af7b5e312fa5606fa63088f13ae8d42246896d3f031957dd14f"
metafile = true

[[files]]
file = "datapacks/data-double-shulker-shells.pw.toml"
hash = "7d26977d5252de0d83aac8fd2215bab1491dc3c4a528591abd11b804fc1239be"
metafile = true

[[files]]
file = "datapacks/data-durability-ping.pw.toml"
hash = "5dd80ac623955d174a7ebfc1b72944b4174c9a083fbadeec335856bbbce42593"
metafile = true

[[files]]
file = "datapacks/data-hard-on-start.pw.toml"
hash = "c28706fef6c4451a71f8aa05b633c6529226bc7dd61526c8fca9fc44238d500b"
metafile = true

[[files]]
file = "datapacks/data-model-applier-v3.pw.toml"
hash = "7686cef4a8531e380d062c924f7cf6beb27ea0863f4fbc514caf7701b79e338f"
metafile = true

[[files]]
file = "datapacks/data-more-mob-heads.pw.toml"
hash = "14385cea05a8ece5fda2eb9ab116d761fb8903b6231727b7cdd7101036788a63"
metafile = true

[[files]]
file = "datapacks/data-multiplayer-sleep.pw.toml"
hash = "919e190b7573d1f76f1fa1269863e8fee7c68413dfb11b39b6a49914cfc6323c"
metafile = true

[[files]]
file = "datapacks/data-nether-portal-coords.pw.toml"
hash = "6b457ecfe4b8de43174952797dc7ffd70bbd28cf268e6a0758d3be518ff599e5"
metafile = true

[[files]]
file = "datapacks/data-painting-picker.pw.toml"
hash = "029bdb8492adde41b6d266672b6e9056298194d3023b6005303feb0042bf2ea6"
metafile = true

[[files]]
file = "datapacks/data-player-head-drops.pw.toml"
hash = "d753ee21e7f89d15850ce9a7ee9c36870cd8c55e8af57e61e352324a27f03a79"
metafile = true

[[files]]
file = "datapacks/data-silence-mobs.pw.toml"
hash = "4d3b06741fa93cd90765ffade470cb7398ee5454c6febfc3e22a249d9988e023"
metafile = true

[[files]]
file = "datapacks/data-spectator-conduit-power.pw.toml"
hash = "159ebca07142c88931b625441f82517aeb787e114c68c05b73efd5640059b44e"
metafile = true

[[files]]
file = "datapacks/data-spectator-night-vision.pw.toml"
hash = "f2f5111c223cbb528fdc494057bbd845243fb4404049923814df785075361c8d"
metafile = true

[[files]]
file = "datapacks/data-storm-channeling.pw.toml"
hash = "bf52d1596180e17fc16313d15f44d6c847eebb5f76291467b997166f40b408a8"
metafile = true

[[files]]
file = "datapacks/data-toggle-weather.pw.toml"
hash = "6fb5b8d4afe0066f69fa4d9bfef4daf94c1be2559165656be8953c2df23e15a0"
metafile = true

[[files]]
file = "datapacks/data-tp-tools.pw.toml"
hash = "82012634476bb2d84e383a6b73bfc9184f4689e6dc1f9a545cad6e236a666d55"
metafile = true

[[files]]
file = "datapacks/data-track-raw-stats.pw.toml"
hash = "ce912f96b0646305a583176506c699a01b17afcbe11ce7c9172c644b46630e0b"
metafile = true

[[files]]
file = "datapacks/data-track-stats.pw.toml"
hash = "37d36cac49d6576f89e655bd58fa5e908eb3d9361a80c52a96b34737b8aea9b7"
metafile = true

[[files]]
file = "datapacks/data-translatable.pw.toml"
hash = "2a5ab0487af1dc20d23690a27621f95e87d08c92ced31249728f7e52d735f4f5"
metafile = true

[[files]]
file = "datapacks/data-universal-dying.pw.toml"
hash = "d7cdda20f1de9e6e7073111872a06cb0ec933aa7df598e5fe0d02af557a3a9cd"
metafile = true

[[files]]
file = "datapacks/data-unlock-recipes-trigger.pw.toml"
hash = "07afe515a2479711ffb7f21b94859d53e75ce2473b2d349640df6eaa2f589917"
metafile = true

[[files]]
file = "datapacks/data-wandering-trades.pw.toml"
hash = "032bc1e52eb024d152bb79437b5cb190644f4533330626b5e0cb4be8bd5c5cb2"
metafile = true

[[files]]
file = "datapacks/name-formatting-station-datapack.pw.toml"
hash = "8728ea0b7c4350299dfb8e4fcaf22807233de5eee4b6295b4d24edb37aeeab73"
metafile = true

[[files]]
file = "modrinth.index.json"
hash = "c4e9297a1d6a15ad1ee098638d795eec6bfb198ec1843c9793611a73aeb959f9"

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "d2416c9882caa02158d22a25ab42c95d096a1d00e796e34a46a0c4b6c5267c88"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "0941c5b9cafbbc4bea49d36493abb63b6e392f2bcce6b7381b0283dfc3eaec94"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "67c1fc85b89261af425055417fe6e85e4981b7d61662fe4f79d50a734e9738da"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "524e841aab4137340a1278b681268b024db28e8ad874857f0ada93db77a8d8d3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabricexporter.pw.toml"
hash = "5b0491bcaad6a280809d8abc33eb20a9613fec528d29b645567aad981fff4972"
metafile = true

[[files]]
file = "mods/inhabitor.pw.toml"
hash = "b351ee9591829c17aab30b6e94edf07e14be48b830c7bfb2b3e7e5eb6d05443f"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "e87a4eb7527e13fab94b671ce1d267cfc4d6093a3c3c1fbab7f135fb413727dc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/sha1runtime.pw.toml"
hash = "9a325a6dfe6ae84c34b579885520ecceb7a01cbc9bf18c95860b6dfb305b5022"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "231fcca76d289ac462cfcbc4ec351dba6999a98e70d7c535ddef47b1ee069379"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "af324ff6ff0e13779b645d543d77c725f71628feb2a23de2e5e053bfa94532f9"
metafile = true

[[files]]
file = "overrides/datapacks/ModelApplierV3.zip"
hash = "e549d0b68c867bf9c39476ac66ab9be10289de6639bf4e051c622002007559dc"

[[files]]
file = "overrides/datapacks/afk display v1.1.14 (MC 1.21-1.21.10).zip"
hash = "8b961fb93fba3e76bb1ec972126fb2ba281d1bd6ad97abd344f35b51e178b834"

[[files]]
file = "overrides/datapacks/anti enderman grief v1.1.14 (MC 1.21-1.21.10).zip"
hash = "bb4d64fe6fde9edad5bacb21a960d8b973c32d1f5eaf60128306eebe1e2e5836"

[[files]]
file = "overrides/datapacks/camera-v1.4.zip"
hash = "2f6f2be6a1f525289232c831145b34679f0f53475df93f27988ef45a900b7171"

[[files]]
file = "overrides/datapacks/cave-cleaner-v1.5.zip"
hash = "2dc6e361ac4e81287fc0d09bf29ecd306014d83507a8d6c1ac5b2ccd17644f01"

[[files]]
file = "overrides/datapacks/coordinates hud v1.2.15 (MC 1.21-1.21.10).zip"
hash = "ac57d0b8d19cc3b3caf7719eee0a67e25765e5b95790e85091c9c58ad447b5e0"

[[files]]
file = "overrides/datapacks/double shulker shells v1.3.14 (MC 1.21-1.21.10).zip"
hash = "a63d05018a10fcf5fb488a89eed8a952d26b17cc4ce0320ba4c1b1ec86e41c30"

[[files]]
file = "overrides/datapacks/durability ping v1.1.15 (MC 1.21-1.21.10).zip"
hash = "1ddb8e9e88a307253d0a7700f6fbc3158685d047f8782a06cd0a593fea2d900d"

[[files]]
file = "overrides/datapacks/hard-on-start-v1.5.zip"
hash = "bbf468bf6e81b4fdabb0ccc55bd1baba0c5d39825a3507b5a8e0a7c4ca138dfd"

[[files]]
file = "overrides/datapacks/more mob heads v2.17.3 (MC 1.21-1.21.10).zip"
hash = "c2162acc3bbcaf1dae9aaf7398438772d3429b7218a25801924c3094158863c2"

[[files]]
file = "overrides/datapacks/multiplayer sleep v2.6.14 (MC 1.21-1.21.10).zip"
hash = "6218f82f661ead5c08866ff618070ffe6e48609ec98b08b0d51d8900bb9a5c16"

[[files]]
file = "overrides/datapacks/nether portal coords v1.1.14 (MC 1.21-1.21.10).zip"
hash = "91cb0ca7a97af6abc596fa271dfd88619a1504d3056fb563cb029e4134c07902"

[[files]]
file = "overrides/datapacks/painting picker v1.1.1 (MC 1.21-1.21.10).zip"
hash = "d0bd826998dd807d9e74dff7ceec6a99163f6b40fc0986e621a41f5bc640a424"

[[files]]
file = "overrides/datapacks/player head drops v1.1.14 (MC 1.21-1.21.10).zip"
hash = "310354d54ed65f619903dd07f1a5fcdb1fae47a4c39d234fbe39cb373040755c"

[[files]]
file = "overrides/datapacks/silence mobs v1.2.8 (MC 1.21-1.21.10).zip"
hash = "934db02ab188038041283033a0eb4fea0aa6e9bc08d50b39e2c9c26fdac73747"

[[files]]
file = "overrides/datapacks/spectator conduit power v1.1.14 (MC 1.21-1.21.10).zip"
hash = "6b029f393c39e5b88820fad2563e8c7d7d3004f78f21d99ac573d755b8ac9c35"

[[files]]
file = "overrides/datapacks/spectator night vision v1.1.14 (MC 1.21-1.21.10).zip"
hash = "dd0f9e92bb78c99ecaab0c7bca1796180e4ee06e86b7538169161bc5824da569"

[[files]]
file = "overrides/datapacks/storm channeling v1.0.6 (MC 1.21-1.21.10).zip"
hash = "725d310709c4a0b1d29f2ec2e9eed3311e250d260b21abf6d8d1c213f13745ee"

[[files]]
file = "overrides/datapacks/toggle-weather-v1.5.zip"
hash = "172df9de7383102e9da08660757903e9090f2a53f4fb3379693758ca80c1c249"

[[files]]
file = "overrides/datapacks/tp-tools-v1.6.zip"
hash = "08d71a9fb331300b6b98cdf0e946980ae715fba5113973aa21605803264b8c53"

[[files]]
file = "overrides/datapacks/track raw statistics v1.7.10 (MC 1.21-1.21.10).zip"
hash = "eddbf5ea9423948683926f66373c88fb5df579e8a8d749f5ab87885f134f3f3d"

[[files]]
file = "overrides/datapacks/track statistics v1.1.16 (MC 1.21-1.21.10).zip"
hash = "11f38cc559f12f3596fcb0cb5cb30a702f9bdade7e05c400a212a6b885526f36"

[[files]]
file = "overrides/datapacks/translatable_v1.9.zip"
hash = "19dda5e675255ef9ae0b25088ba74b9072d21cc8f185a16518cab487d8d15971"

[[files]]
file = "overrides/datapacks/universal dying (MC 1.21-1.21.10).zip"
hash = "4413ebe1a8af267bfa424aef2519fc3e1c2df6a7293cb63652eb3cba5c486443"

[[files]]
file = "overrides/datapacks/unlock_recipes_trigger.zip"
hash = "ec99e0809f0e54de91a0a3f90666fb0eef41443f490808ef7869ba393a0394ca"

[[files]]
file = "overrides/datapacks/wandering trades v1.7.13 (MC 1.21-1.21.10).zip"
hash = "7f7ae305e80e61cf2b493d0feae5ffd3ea237eea4c14f6636f8aa2a90200f83c"

[[files]]
file = "readme.md"
hash = "96e06927520f8bb80f38dc0158c71965ea335f93210d955390d36a3e78aa9f07"

[[files]]
file = "unsup.toml"
hash = "1029dc302d8c81ca75dcfcb8d81d6bde3b35cc2918a99d77e3d61ed118637580"
