hash-format = "sha256"

[[files]]
file = "datapacks/armor-statues-datapack.pw.toml"
hash = "c9d215756d276588de476a1b5905bef6c7b0f0e138de8064aa94cdc28533bf10"
metafile = true

[[files]]
file = "datapacks/camera.pw.toml"
hash = "b8900462652023b6be921841a7c79464b86c1474af6bf9c60cb05918b1a8d15b"
metafile = true

[[files]]
file = "datapacks/cave-cleaner.pw.toml"
hash = "36cda8dbf3891f2e759036ac4d6a2a246e898e296e72a6516b1309baee43f76e"
metafile = true

[[files]]
file = "datapacks/data-model-applier-v3.pw.toml"
hash = "b569621e42af7443373199912f1525e908591d30a1a4ad56c3a441678b5c6b79"
metafile = true

[[files]]
file = "datapacks/data-translatable.pw.toml"
hash = "792db76eb1423de5b3b0430303048d1fda2497f37cca9e74c35ccfc75cd19c2f"
metafile = true

[[files]]
file = "datapacks/hard-on-start.pw.toml"
hash = "702835687c8e38265aa4ed3e34aaff7f406d48fea54377508673ccac578f2aa8"
metafile = true

[[files]]
file = "datapacks/name-formatting-station-datapack.pw.toml"
hash = "8728ea0b7c4350299dfb8e4fcaf22807233de5eee4b6295b4d24edb37aeeab73"
metafile = true

[[files]]
file = "datapacks/toggle-weather.pw.toml"
hash = "4b7a2dce99e1fd64b8373f9c06e4ae737e33c32d334c1f9a1b66f934a47fe2c7"
metafile = true

[[files]]
file = "datapacks/tp-tools.pw.toml"
hash = "d332b873abc99de0d683033b98fc8087a713f884da233facdda97fe64acf471b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "d2416c9882caa02158d22a25ab42c95d096a1d00e796e34a46a0c4b6c5267c88"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "0941c5b9cafbbc4bea49d36493abb63b6e392f2bcce6b7381b0283dfc3eaec94"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "0468ce45030e77dc9b3a848b01014e8bb7a3fb7f65bc8db3efde2d0b438498d3"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "96d9c2cae594552c3507b24e7dbd97ac00967d0a1104a01a677f17bfc2140d11"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0e073702f4562edac6258fd01f8b921628adf48fdd7e70209d93f4978753a0ce"
metafile = true

[[files]]
file = "mods/chat-signing-hider.pw.toml"
hash = "8cb0488195af61cf03d34b4e88ad0ef4baedfd093ae647e7a0704905d10ba37c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "67c1fc85b89261af425055417fe6e85e4981b7d61662fe4f79d50a734e9738da"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b06a7f30dcd9f9df9d10998274ee6b419c59f2a61a07833aafc2a62b929d3bec"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "524e841aab4137340a1278b681268b024db28e8ad874857f0ada93db77a8d8d3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabricexporter.pw.toml"
hash = "5b0491bcaad6a280809d8abc33eb20a9613fec528d29b645567aad981fff4972"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "9d12f51a932b25751b7595ca46439a30bee2c26bf6d9913ccc9a27ade1972f36"
metafile = true

[[files]]
file = "mods/inhabitor.pw.toml"
hash = "b351ee9591829c17aab30b6e94edf07e14be48b830c7bfb2b3e7e5eb6d05443f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "e87a4eb7527e13fab94b671ce1d267cfc4d6093a3c3c1fbab7f135fb413727dc"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "8c75e0407d200803b12333bc2dc59f25b3e0060aa3f07ccfa59ebaa194acd560"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "865f5bd5909c8710e14b253f1b29e0b40119af2a824b80141dc9943f98af5b4d"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "df5ce30f6ac464f7b06400e03568d2b9087dd1849fd8c21a2381fe2f666338b6"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "2d373a1128cdb01a77053c64d5d6a64cf76c2d68da0529b2cc0f2dd6f8371767"
metafile = true

[[files]]
file = "mods/model-browser.pw.toml"
hash = "db8e3134b1920ffc380d037420142be6dc9f26f6a8007f96625b0dc833a16962"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "22e9b5d9795e000d5da783c974f0653993b110ae59e1e7cac0c082e206004934"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "4e5f9a4fbef8a03ea0f9dbd8cc60540b8a58491e3f84716213ab1a5792403ddc"
metafile = true

[[files]]
file = "mods/replay-voice-chat.pw.toml"
hash = "b05d7d1a0bbd933633cebd1d5e846205a8c0c49fc2129835e1c3d193c1cfa44e"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "89837eaa44abe7bb598faf2012531f5a3335b1c413624c6eff44031e8ec48238"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "655bc945df6491a4f22eea0429f10b20447e48488ba0794cb301bd6e7cc465dd"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "cb4cce65ff8a0cf0a88fe8cb3d321f94f9d7f6a27b0a20631c9352ec0a2778ba"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
hash = "0b522c2afe15365b0535e5a744e9c2652f5289fcfbdf328c438212b55dd89834"
metafile = true

[[files]]
file = "mods/sha1runtime.pw.toml"
hash = "9a325a6dfe6ae84c34b579885520ecceb7a01cbc9bf18c95860b6dfb305b5022"
metafile = true

[[files]]
file = "mods/shadeandsaturation.pw.toml"
hash = "f05f7e3a3b09305673ca2fa8868367fdffb929555ef3ea4edbcd92806923328a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c9fd548aa345384fe05cc143a191e6e507a07c20a08f31562966f5423a4e39d9"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "231fcca76d289ac462cfcbc4ec351dba6999a98e70d7c535ddef47b1ee069379"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "af324ff6ff0e13779b645d543d77c725f71628feb2a23de2e5e053bfa94532f9"
metafile = true

[[files]]
file = "overrides/datapacks/ModelApplierV3.zip"
hash = "e549d0b68c867bf9c39476ac66ab9be10289de6639bf4e051c622002007559dc"

[[files]]
file = "overrides/datapacks/translatable_v1.9.zip"
hash = "19dda5e675255ef9ae0b25088ba74b9072d21cc8f185a16518cab487d8d15971"

[[files]]
file = "unsup.toml"
hash = "4bb42a6defe3f9ab6beec8592101ff7f4ae5603938c32b2f70d65af9dfbe9ea3"
