hash-format = "sha256"

[[files]]
file = "datapacks/armor-statues-datapack.pw.toml"
hash = "c9d215756d276588de476a1b5905bef6c7b0f0e138de8064aa94cdc28533bf10"
metafile = true

[[files]]
file = "datapacks/camera.pw.toml"
hash = "8961659c6fc630d9edb5e5539bf3701a56d894638d7046364c62f2e76184bf6a"
metafile = true

[[files]]
file = "datapacks/cave-cleaner.pw.toml"
hash = "daa15797d5c018beb4fa5c855ad35e6731a7e387dcf63568d597563a10d1f819"
metafile = true

[[files]]
file = "datapacks/hard-on-start.pw.toml"
hash = "b6095352524c5e72084aa52e8328887bd81290b191027d1d01e2ba5041434b8e"
metafile = true

[[files]]
file = "datapacks/model-applier-v3.pw.toml"
hash = "b569621e42af7443373199912f1525e908591d30a1a4ad56c3a441678b5c6b79"
metafile = true

[[files]]
file = "datapacks/name-formatting-station-datapack.pw.toml"
hash = "8728ea0b7c4350299dfb8e4fcaf22807233de5eee4b6295b4d24edb37aeeab73"
metafile = true

[[files]]
file = "datapacks/restart-redstone.pw.toml"
hash = "d354a8204bb9df5b083849901db896fb3f596a2c3828f8ec53d2fadd4c75a6cf"
metafile = true

[[files]]
file = "datapacks/toggle-weather.pw.toml"
hash = "7c36c17a3a93b3bc97e831fc8615a0baaa92a14502d5189727ee65ec246cbaaf"
metafile = true

[[files]]
file = "datapacks/tp-tools.pw.toml"
hash = "e609725700450e64deba0b55944a911eb1c51f4e7fe3c0e4dcc9fac1036c0086"
metafile = true

[[files]]
file = "datapacks/translatable.pw.toml"
hash = "792db76eb1423de5b3b0430303048d1fda2497f37cca9e74c35ccfc75cd19c2f"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "d2416c9882caa02158d22a25ab42c95d096a1d00e796e34a46a0c4b6c5267c88"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "0941c5b9cafbbc4bea49d36493abb63b6e392f2bcce6b7381b0283dfc3eaec94"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "6088be62ff0bc4e93388ba995418a376a1b7dfd062cce84bc36349b34ffa4af6"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "0468ce45030e77dc9b3a848b01014e8bb7a3fb7f65bc8db3efde2d0b438498d3"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "96d9c2cae594552c3507b24e7dbd97ac00967d0a1104a01a677f17bfc2140d11"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0e073702f4562edac6258fd01f8b921628adf48fdd7e70209d93f4978753a0ce"
metafile = true

[[files]]
file = "mods/chat-signing-hider.pw.toml"
hash = "8cb0488195af61cf03d34b4e88ad0ef4baedfd093ae647e7a0704905d10ba37c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "67c1fc85b89261af425055417fe6e85e4981b7d61662fe4f79d50a734e9738da"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b06a7f30dcd9f9df9d10998274ee6b419c59f2a61a07833aafc2a62b929d3bec"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "524e841aab4137340a1278b681268b024db28e8ad874857f0ada93db77a8d8d3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabricexporter.pw.toml"
hash = "5b0491bcaad6a280809d8abc33eb20a9613fec528d29b645567aad981fff4972"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
hash = "e56ab572b86cd0f11f62baa45556a21cf767197a6f028d967814166b10ed3784"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "9d12f51a932b25751b7595ca46439a30bee2c26bf6d9913ccc9a27ade1972f36"
metafile = true

[[files]]
file = "mods/inhabitor.pw.toml"
hash = "b351ee9591829c17aab30b6e94edf07e14be48b830c7bfb2b3e7e5eb6d05443f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "e87a4eb7527e13fab94b671ce1d267cfc4d6093a3c3c1fbab7f135fb413727dc"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "8c75e0407d200803b12333bc2dc59f25b3e0060aa3f07ccfa59ebaa194acd560"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "865f5bd5909c8710e14b253f1b29e0b40119af2a824b80141dc9943f98af5b4d"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "df5ce30f6ac464f7b06400e03568d2b9087dd1849fd8c21a2381fe2f666338b6"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "2d373a1128cdb01a77053c64d5d6a64cf76c2d68da0529b2cc0f2dd6f8371767"
metafile = true

[[files]]
file = "mods/model-browser.pw.toml"
hash = "db8e3134b1920ffc380d037420142be6dc9f26f6a8007f96625b0dc833a16962"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "22e9b5d9795e000d5da783c974f0653993b110ae59e1e7cac0c082e206004934"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "4e5f9a4fbef8a03ea0f9dbd8cc60540b8a58491e3f84716213ab1a5792403ddc"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "655bc945df6491a4f22eea0429f10b20447e48488ba0794cb301bd6e7cc465dd"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "cb4cce65ff8a0cf0a88fe8cb3d321f94f9d7f6a27b0a20631c9352ec0a2778ba"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
hash = "0b522c2afe15365b0535e5a744e9c2652f5289fcfbdf328c438212b55dd89834"
metafile = true

[[files]]
file = "mods/sha1runtime.pw.toml"
hash = "9a325a6dfe6ae84c34b579885520ecceb7a01cbc9bf18c95860b6dfb305b5022"
metafile = true

[[files]]
file = "mods/shadeandsaturation.pw.toml"
hash = "f05f7e3a3b09305673ca2fa8868367fdffb929555ef3ea4edbcd92806923328a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c9fd548aa345384fe05cc143a191e6e507a07c20a08f31562966f5423a4e39d9"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "231fcca76d289ac462cfcbc4ec351dba6999a98e70d7c535ddef47b1ee069379"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "af324ff6ff0e13779b645d543d77c725f71628feb2a23de2e5e053bfa94532f9"
metafile = true

[[files]]
file = "unsup.toml"
hash = "116182138e4cbb51cae1cde9ddcca77d61a158fbcb0b6cb87452108e8a4414df"
