hash-format = "sha256"

[[files]]
file = "datapacks/camera.pw.toml"
hash = "3103adcb641824c403e04378a6196a1969b3067974d7584e54e49fdfdf2877f6"
metafile = true

[[files]]
file = "datapacks/cave-cleaner.pw.toml"
hash = "2ba4d806c0dde16305455ad76baf87488e231177c7a954d92d3ab9d2a6842862"
metafile = true

[[files]]
file = "datapacks/hard-on-start.pw.toml"
hash = "8264ed07026da13dcc4dcca3ba231d9c2ef0a3d11347592bbd1b85ece104ee16"
metafile = true

[[files]]
file = "datapacks/model-applier-v3.pw.toml"
hash = "6bb72a209ed057de029fca80249d9b5b6cd77c79a77f48a059786c0956052055"
metafile = true

[[files]]
file = "datapacks/restart-redstone.pw.toml"
hash = "017410a0c22d20f99c2ec5d0a47c487651b37e8445fb79e8a7ca05006aae6eef"
metafile = true

[[files]]
file = "datapacks/toggle-weather.pw.toml"
hash = "1422beb60a9a4397b03071a052a4d3f4f85be89cc8b265aa49d88992c0f6c0a3"
metafile = true

[[files]]
file = "datapacks/tp-tools.pw.toml"
hash = "9b66e90b3eeea489e2c213acfd5eacc72cd7d509c2e3725bf02d572ecfed8ffc"
metafile = true

[[files]]
file = "datapacks/translatable.pw.toml"
hash = "32a2629baa2ec6a672415555ca29783977f2872331663de130b30e272fa1c812"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "236561ef92acc118a8fd885d653633a76498c39d77f3346f62024fdb0cf365d8"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "bb8025266b673ca78df53261a871cff669c6cfe89ce1afb0809fa515782d0dcd"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "2e68a00913f23cf93921f6f034435b5d90fd9b7d1a0a2aaa294123a18c140bdc"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "cbf0ba115415b693b167a3d4282b8da12283665d6c6567a2b99028ba903d0de1"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "eda6f502a577f43ac8f1511fb544b60addbd7d2e12a30ae4b9bac2f2e4737c16"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "7266ff1544ce05de4585edb60b35dc52bbf4f082f441b4dacb29c24e3a4ae653"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1a33c4f72a7c90eb5d1ea37297517c144f73c05a5bd387daa91d5fb43c03ca56"
metafile = true

[[files]]
file = "mods/chat-signing-hider.pw.toml"
hash = "6990d7de24d07a624128d2692dda43ed3960c7985b34ccd1c54af4befaf6ee68"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "8a2c564b4b7b8ce6642c25d517920ac12199a09c57ee850044276185f491a84a"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "6cb1c99c8dbb634bd595f0b348e7ebe769ba34b89421e1c78bcfcb3ad07ee761"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "a7638d53a7f77783f50d21aa1bb37d94c5959debf3039e7be00ac80a3116ffae"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6cf5d35544d91a3bf197002762bacbecb8e778f7ad8a56a2abb5832c7df12a80"
metafile = true

[[files]]
file = "mods/inhabitor.pw.toml"
hash = "266cda229d079271cf513c5605a9523eca2a9e9e58d26e58f430c96d9d737075"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f26bee145b9df8a97fcc0263cafb2a3dc0d7bef95c34f565cab7eefe856d19d2"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "a98087fdda7661c5b9aa9cb78b18afc617a96564d355eb1e3701dfe29d87ab09"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "f880ae93d36834a12ab9bb324cd80d42ac1b45314a39afe25350d94167d3e894"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3075f8789416a6beb37baf55f5278a829db22b65216279ad25cdefd1d5b78fa2"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "c27b37804e981bb6d7029decacf23f82ed02121655d6cee7698a764e36750ea7"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "5fa5110cbc53544de247c95aab312c4d6051ac7c228982d2235c46ea5f552a76"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "16d49fc88b0f3691ad27855aa8f5c45ff5660294ef396c8d62ea2f81e56ff024"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "89cedb686d76c3be65da8cd097c8bbb980b087eb99ee46152a8114f743946224"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "df76ef2e4e592a3c8a31ad8252af0f5d394b4047e6178d1c931ba4df0baa2cc2"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "c7cc3907e7adb7b30249dc2b5ccd3e30111d562475087e0188f00fb3bc5837de"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "6299ddae25bfd043fb32a284c2f56b4d437d1b7b6d2efc2ee32195a6ec7fd13b"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "09a625876461177af3ed00af306f95f24dbb3beb43e7886c0c59301ca583dfc2"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "0f2d8700300feb2cbe583b3cbb1823afd6f048f746c3c8d38a29dc75f0d598c0"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
hash = "2260089b3f0b06fe4aef31b3e159800ba1f06d67841e2f66383f4077f78885f6"
metafile = true

[[files]]
file = "mods/sha1runtime.pw.toml"
hash = "780c048794737e1769f78ae627c73a724575b7f56a26ede1ddc98960c222e589"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "5910b518564845e59395843f721a51fd03f06eb4e1e7a5fafcb9cd36e8cc6f34"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cb797d599dbba167d104449bc62a7485d1ddbf2368f1a40f3c2e3996768ae97a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "cb76fc7cfef970ac40ed8cf48d76658f3095d88a81f847ef5704c86450cbd745"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "ab679c91b1aa16e4fd8eb2ebecd2a656a6c84e7b4c440449809ac85e880ed2d2"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "dc89329ab457f8724414c7d63ff612c678d3976ac25e489633201b57827492e8"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "f87e92d262ffe55d3f2406d2bbc9316200f5726c1478655a0780d49f8ebdd81f"
metafile = true

[[files]]
file = "unsup.toml"
hash = "116182138e4cbb51cae1cde9ddcca77d61a158fbcb0b6cb87452108e8a4414df"
