name = "Hermitcraft Server"
author = "henkelmax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f243bda23ee4ff413a5697cf070b76d7a88d494f2a67ef34093c713308507f4"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
