name = "Hermitcraft Server"
author = "henkelmax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7ab21fa4665295a747ccb94ad4a33408e85327b8d3d370d1cbb4ee063a379a9"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
