name = "Hermitcraft Server"
author = "henkelmax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "786777cc3be3d38e729085bbd85b0498a0354fc1019ee01a10269e0a1326a047"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
datapack-folder = "datapacks"
