name = "Hermitcraft Server"
author = "henkelmax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9e2ebf0b374fb9aa75b5eab8be5f58ef140eaa662e214cb1dc6e8181f2a4d47"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
