name = "oce server"
author = "henkelmax (hermitcraft-server) & JustPyrrha (oce server)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98604399abff0f2d08f73552e1b1fef332cb6470b2278660370a1fdf188df68c"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
