name = "Hermitcraft Server"
author = "henkelmax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b17f37cc4c14dd6985a5891d0eb5366948f04850bd06ad2bd5943d73a9fa105d"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
