[flavor_groups.client]
name = "Client Pack Variant"
side = "client"
description = "We provide two versions of the client modpack.\nIf you don't know what to choose, just pick Recommended."
[[flavor_groups.client.choices]]
id = "client_recommended"
name = "Recommended"
description = "Recommended mod setup for those who just want to play and don't care what mods they have."
[[flavor_groups.client.choices]]
id = "client_minimal"
name = "Minimal"
description = "The minimum set of required mods to connect to the server. Recommended if you have experience with modding Minecraft and have a set of mods you like to play with. You can add your own mods via Prism Launcher's Mods page.\nNote: This is missing a lot of QoL mods that Recommended includes."


# baseline client mods
[metafile.armor-poser]
flavors = ["client_minimal", "client_recommended"]
[metafile.cloth-config]
flavors = ["client_minimal", "client_recommended"]
[metafile.datapack-injector]
flavors = ["client_minimal", "client_recommended"]
[metafile.fabric-api]
flavors = ["client_minimal", "client_recommended"]
[metafile.itemswapper]
flavors = ["client_minimal", "client_recommended"]
[metafile.lithium]
flavors = ["client_minimal", "client_recommended"]
[metafile.simple-voice-chat]
flavors = ["client_minimal", "client_recommended"]
[metafile.status]
flavors = ["client_minimal", "client_recommended"]

# recommended client mods
[metafile.appleskin]
flavors = ["client_recommended"]
[metafile.bundles-beyond]
flavors = ["client_recommended"]
[metafile.camera-utils]
flavors = ["client_recommended"]
[metafile.chat-heads]
flavors = ["client_recommended"]
[metafile.chat-signing-hider]
flavors = ["client_recommended"]
[metafile.ears]
flavors = ["client_recommended"]
[metafile.freecam]
flavors = ["client_recommended"]
[metafile.iris]
flavors = ["client_recommended"]
[metafile.locator-heads]
flavors = ["client_recommended"]
[metafile.malilib]
flavors = ["client_recommended"]
[metafile.minihud]
flavors = ["client_recommended"]
[metafile.model-browser]
flavors = ["client_recommended"]
[metafile.modmenu]
flavors = ["client_recommended"]
[metafile.ok-zoomer]
flavors = ["client_recommended"]
[metafile.peek]
flavors = ["client_recommended"]
[metafile.raised]
flavors = ["client_recommended"]
[metafile.respackopts]
flavors = ["client_recommended"]
[metafile.scribble]
flavors = ["client_recommended"]
[metafile.server-resource-pack-checker]
flavors = ["client_recommended"]
[metafile.shadeandsaturation]
flavors = ["client_recommended"]
[metafile.shulkerboxtooltip]
flavors = ["client_recommended"]
[metafile.sodium]
flavors = ["client_recommended"]
